/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arackiralama;

import Islemler.AracIslemleri;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import tablo.Araclar;

/**
 *
 * @author baior
 */
public class AracList extends javax.swing.JFrame {
DefaultTableModel model;
    AracIslemleri aracIslemleri = new AracIslemleri();
    int aracID;
    
    public AracList() {
        initComponents();
        
        model = (DefaultTableModel) Aractablo.getModel(); 
        AracListele();
    }

    public void AracListele(){
        model.setRowCount(0);
        ArrayList<Araclar> AraclarListesi = new ArrayList<Araclar>();
        
        AraclarListesi = aracIslemleri.Listele();
        
        if (AraclarListesi != null) {
            
            for (Araclar arac : AraclarListesi) {
                
                String durum = "kiralanamaz";
                if (arac.getAktifMi() == 1) {
                    durum = "kiralanabilir";
                }
                
                Object[] eklenecek = {arac.getPlaka(),arac.getMarka(),arac.getModel(),arac.getUretimYili(),
                    arac.getYakitTuru(),arac.getKapiSayisi(),arac.getMotorHacmi(),arac.getKasaTipi(),arac.getSanzimanTipi(),
                    arac.getKoltukSayisi(),arac.getEhliyetSinifi(),durum,arac.getTutar(),arac.getAracID()};
                model.addRow(eklenecek);
            }
        }
    }
    public void DinamikAra(String p){
        
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        
        Aractablo.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(p));
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbyakitturu = new javax.swing.JComboBox<>();
        cbehliyet = new javax.swing.JComboBox<>();
        txtplaka = new javax.swing.JTextField();
        cbsanziman = new javax.swing.JComboBox<>();
        txtmarka = new javax.swing.JTextField();
        cbkasatipi = new javax.swing.JComboBox<>();
        txtmodel = new javax.swing.JTextField();
        txturetimtarihi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtmotor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtkapisayisi = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtkoltukSayisi = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        update = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Aractablo = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        aramacubugu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txttutarveri = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbyakitturu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Benzin", "Elektirik", "Dizel", "Lpg" }));

        cbehliyet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));

        cbsanziman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manuel", "Otomatik" }));

        cbkasatipi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedan", "Hatchback", "Cabrio", "SUV", "TIR", "Otobüs" }));

        jLabel9.setText("Motor hacmi: ");

        jLabel10.setText("Kasa tipi:");

        jLabel1.setText("Plaka:");

        jLabel11.setText("Sanzıman tipi:");

        jLabel12.setText("Koltuk sayisi:");

        jLabel2.setText("Marka:");

        jCheckBox1.setText("Durum");

        update.setText("Guncelle");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jLabel3.setText("Model:");

        delete.setText("Sil");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jLabel13.setText("Ehliyet sınıfı:");

        jLabel4.setText("Üretim tarihi:");

        Aractablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Plaka", "Marka", "Model", "Uretim Yılı", "yakıt", "Kapı sayısı", "Hacmi", "Tipi", "Sanzıman", "Koltuk Sayısı", "Ehliyet tipi", "Durum", "Tutar", "ID"
            }
        ));
        Aractablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AractabloMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Aractablo);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel7.setText("Araç Listesi");

        jLabel5.setText("Yakıt türü:");

        aramacubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                aramacubuguKeyReleased(evt);
            }
        });

        jLabel6.setText("Kapı sayısı:");

        close.setText("İptal");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        jLabel14.setText("tutar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtmarka, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtplaka, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txturetimtarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbyakitturu, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtkapisayisi, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmotor, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbsanziman, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtkoltukSayisi, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbehliyet, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbkasatipi, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txttutarveri, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                    .addComponent(aramacubugu))
                .addGap(7, 7, 7))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtplaka, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmarka, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbkasatipi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txturetimtarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbyakitturu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtkapisayisi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtmotor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)
                                        .addComponent(cbsanziman, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(104, 104, 104))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtkoltukSayisi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbehliyet, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(txttutarveri, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(aramacubugu))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed

        String plaka = txtplaka.getText();
        String marka = txtmarka.getText();
        String model = txtmodel.getText();
        int uretimYili =Integer.parseInt(txturetimtarihi.getText());
        String yakitTuru = (String) cbyakitturu.getSelectedItem();
        int kapiSayisi =Integer.parseInt(txtkapisayisi.getText());
        Float MotorHacmi = Float.valueOf(txtmotor.getText());
        String kasaTipi = (String) cbkasatipi.getSelectedItem();
        String sanzimanTipi = (String) cbsanziman.getSelectedItem();
        int koltukSayisi =Integer.parseInt(txtkoltukSayisi.getText());
        String ehliyet = (String) cbehliyet.getSelectedItem();
        int aktifmi = 0;
        if (jCheckBox1.isSelected()) {
            aktifmi = 1;
        }
        int id = aracID;
        int tutar = Integer.parseInt(txttutarveri.getText());
        aracIslemleri.guncelle(plaka, marka, model, uretimYili, yakitTuru, kapiSayisi, MotorHacmi, kasaTipi, sanzimanTipi, koltukSayisi, ehliyet, aktifmi, id,tutar);

        System.out.println("guncellendi");
        AracListele();
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed

        int selectetRow = Aractablo.getSelectedRow();
        if (selectetRow == -1) {
            if (model.getRowCount() == 0) {
                System.out.println("boş");
            }else{
                System.out.println("seçiniz");
            }
        }else{

            int id = (int) model.getValueAt(selectetRow, 12);
            aracIslemleri.sil(id);
            AracListele();
        }

    }//GEN-LAST:event_deleteActionPerformed

    private void AractabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AractabloMouseClicked
        int selectetRow = Aractablo.getSelectedRow();
        txtplaka.setText( model.getValueAt(selectetRow, 0).toString());
        txtmarka.setText( model.getValueAt(selectetRow, 1).toString());
        txtmodel.setText( model.getValueAt(selectetRow, 2).toString());
        txturetimtarihi.setText( model.getValueAt(selectetRow, 3).toString());

        //yakit turu komboboxsa ekleme
        cbyakitturu.removeAllItems();
        String yakit = model.getValueAt(selectetRow, 4).toString();
        cbyakitturu.addItem(yakit);
        if (!yakit.equals("Benzin")) {
            cbyakitturu.addItem("Benzin");
        }
        if (!yakit.equals("Elektirik")) {
            cbyakitturu.addItem("Elektirik");
        }
        if (!yakit.equals("Dizel")) {
            cbyakitturu.addItem("Dizel");
        }
        if (!yakit.equals("Lpg")) {
            cbyakitturu.addItem("Lpg");
        }

        txtkapisayisi.setText( model.getValueAt(selectetRow, 5).toString());
        txtmotor.setText( model.getValueAt(selectetRow, 6).toString());

        //kasa tipi turu komboboxsa
        cbkasatipi.removeAllItems();
        String KasaTipi = model.getValueAt(selectetRow, 7).toString();
        cbkasatipi.addItem(KasaTipi);
        if (KasaTipi.equals("Sedan")) {
            cbkasatipi.addItem("Sedan");
        }
        if (KasaTipi.equals("Hatchback")) {
            cbkasatipi.addItem("Hatchback");
        }
        if (KasaTipi.equals("Cabrio")) {
            cbkasatipi.addItem("Cabrio");
        }
        if (KasaTipi.equals("SUV")) {
            cbkasatipi.addItem("SUV");
        }
        if (KasaTipi.equals("Otobüs")) {
            cbkasatipi.addItem("Otobüs");
        }

        //sanzıman turu
        cbsanziman.removeAllItems();
        String Sanziman = model.getValueAt(selectetRow, 8).toString();
        cbsanziman.addItem(Sanziman);
        if (Sanziman.equals("Otomatik")) {
            cbsanziman.addItem("Otomatik");
        }
        if (Sanziman.equals("Manuel")) {
            cbsanziman.addItem("Manuel");
        }

        //ehliyet turu
        cbehliyet.removeAllItems();
        String ehliyet = model.getValueAt(selectetRow, 10).toString();
        cbehliyet.addItem(ehliyet);
        if (ehliyet.equals("A")) {
            cbehliyet.addItem("A");
        }
        if (ehliyet.equals("B")) {
            cbehliyet.addItem("B");
        }
        if (ehliyet.equals("C")) {
            cbehliyet.addItem("C");
        }
        if (ehliyet.equals("D")) {
            cbehliyet.addItem("D");
        }

        txtkoltukSayisi.setText( model.getValueAt(selectetRow, 9).toString());
        if (model.getValueAt(selectetRow, 11).toString().equals("kiralanabilir")) {
            jCheckBox1.setSelected(true);
        }
        txttutarveri.setText( model.getValueAt(selectetRow,12).toString());
        aracID = (int) model.getValueAt(selectetRow, 13);

    }//GEN-LAST:event_AractabloMouseClicked

    private void aramacubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aramacubuguKeyReleased
        String ara = aramacubugu.getText();
        DinamikAra(ara);
    }//GEN-LAST:event_aramacubuguKeyReleased

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        Giris giris = new Giris();
        giris.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AracList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AracList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AracList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AracList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AracList().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Aractablo;
    private javax.swing.JTextField aramacubugu;
    private javax.swing.JComboBox<String> cbehliyet;
    private javax.swing.JComboBox<String> cbkasatipi;
    private javax.swing.JComboBox<String> cbsanziman;
    private javax.swing.JComboBox<String> cbyakitturu;
    private javax.swing.JButton close;
    private javax.swing.JButton delete;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtkapisayisi;
    private javax.swing.JTextField txtkoltukSayisi;
    private javax.swing.JTextField txtmarka;
    private javax.swing.JTextField txtmodel;
    private javax.swing.JTextField txtmotor;
    private javax.swing.JTextField txtplaka;
    private javax.swing.JTextField txttutarveri;
    private javax.swing.JTextField txturetimtarihi;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
